package ExceptionHandling;

public class Demo {

	public static void main(String[] args) {

		System.out.println("Start of main");
		
		try {
		
			int x = 100;
			int y = 0;
			
			int z = x/y;
			
			System.out.println("x/y is : "+ z);
			System.out.println("end of try");
			
		}
		
		catch(ArithmeticException ae) {
			
			System.out.println("inside Catch ");
			System.out.println(ae.getMessage());;
			
		}
		
		
		
		
		
		
		
		System.out.println("End of main.....");

	}

}
