package ExceptionHandling;

public class Demo {

	public static void main(String[] args) {

		System.out.println("Start of main");
		
		try {
		
			int x = 100;
			String y = "10 ";
			
			int z = x/Integer.parseInt(y);
		
			System.out.println("x/y is : "+ z);
			System.out.println("end of try");
			
		}
		
		catch(ArithmeticException ae) {
			
			System.out.println("inside Catch ");
			System.out.println(ae.getMessage());;
			
		}catch(NumberFormatException nfe) {
			System.out.println("Inside Number format Exception");
		}
		
		
		
		
		
		
		
		System.out.println("End of main.....");

	}

}
